<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk.Razor">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
	</PropertyGroup>

	<PropertyGroup>
		<VersionPrefix>17.0.0-alpha000</VersionPrefix>
		<VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
		<Company>Limbo</Company>
		<Authors>Anders Bjerner, Thomas Nielsen</Authors>
    <Product>Limbo Unused Media</Product>
		<Title>$(Product)</Title>
    <AssemblyTitle>$(Product)</AssemblyTitle>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
	</PropertyGroup>

	<!-- Information for the NuGet package -->
	<PropertyGroup>
		<PackageTags>Limbo, Skybrud, Umbraco, UnusedMedia</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageProjectUrl>https://packages.limbo.works/limbo.umbraco.unusedmedia/v17/</PackageProjectUrl>
		<PackageIcon>Limbo.png</PackageIcon>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/limbo-works/Limbo.Umbraco.UnusedMedia</RepositoryUrl>
	</PropertyGroup>

	<!-- Include additional metadata in the assembly -->
	<ItemGroup>
    <AssemblyMetadata Include="Authors" Value="$(Authors)" />
		<AssemblyMetadata Include="PackageProjectUrl" Value="https://packages.limbo.works/limbo.umbraco.unusedmedia/" />
		<AssemblyMetadata Include="DocumentationUrl" Value="https://packages.limbo.works/limbo.umbraco.unusedmedia/docs/v17/" />
		<AssemblyMetadata Include="NuGetUrl" Value="https://www.nuget.org/packages/Limbo.Umbraco.UnusedMedia" />
		<AssemblyMetadata Include="UmbracoMarketplaceUrl" Value="https://marketplace.umbraco.com/package/limbo.umbraco.unusedmedia" />
	</ItemGroup>

  <!-- Ignore vulnerabilities from transient dependencies -->
  <PropertyGroup>
    <NuGetAuditMode>direct</NuGetAuditMode>
  </PropertyGroup>

  <!-- Include NuGet dependencies -->
	<ItemGroup>
		<PackageReference Include="Skybrud.Essentials" Version="1.1.69" />
		<PackageReference Include="Skybrud.Essentials.Umbraco" Version="17.0.0-alpha008-build202609140707" />
		<PackageReference Include="Umbraco.Cms.Web.Website" Version="[17.1.0,17.9.9)" />
		<PackageReference Include="Umbraco.Cms.Api.Management" Version="[17.1.0,17.9.9)" />
	</ItemGroup>

	<!-- Include package icon for NuGet -->
	<ItemGroup>
		<Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
	</ItemGroup>

  <!-- Include custom appsettings schema -->
  <ItemGroup>
    <None Include="appsettings-schema.Limbo.Umbraco.UnusedMedia.json" Pack="true" PackagePath="" />
    <None Include="buildTransitive\Limbo.Umbraco.UnusedMedia.targets" Pack="true" PackagePath="buildTransitive\" />
  </ItemGroup>

</Project>
